// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SyncCheckResponse_Check_CheckType int32

const (
	SyncCheckResponse_Check_HTTP      SyncCheckResponse_Check_CheckType = 0
	SyncCheckResponse_Check_TCP       SyncCheckResponse_Check_CheckType = 1
	SyncCheckResponse_Check_HEARTBEAT SyncCheckResponse_Check_CheckType = 2
)

var SyncCheckResponse_Check_CheckType_name = map[int32]string{
	0: "HTTP",
	1: "TCP",
	2: "HEARTBEAT",
}
var SyncCheckResponse_Check_CheckType_value = map[string]int32{
	"HTTP":      0,
	"TCP":       1,
	"HEARTBEAT": 2,
}

func (x SyncCheckResponse_Check_CheckType) String() string {
	return proto.EnumName(SyncCheckResponse_Check_CheckType_name, int32(x))
}
func (SyncCheckResponse_Check_CheckType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_4ae8239b4bb1387c, []int{3, 0, 0}
}

type RegistrationRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationRequest) Reset()         { *m = RegistrationRequest{} }
func (m *RegistrationRequest) String() string { return proto.CompactTextString(m) }
func (*RegistrationRequest) ProtoMessage()    {}
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_4ae8239b4bb1387c, []int{0}
}
func (m *RegistrationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationRequest.Unmarshal(m, b)
}
func (m *RegistrationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationRequest.Marshal(b, m, deterministic)
}
func (dst *RegistrationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationRequest.Merge(dst, src)
}
func (m *RegistrationRequest) XXX_Size() int {
	return xxx_messageInfo_RegistrationRequest.Size(m)
}
func (m *RegistrationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationRequest proto.InternalMessageInfo

func (m *RegistrationRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegistrationResponse struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Addr                 string   `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegistrationResponse) Reset()         { *m = RegistrationResponse{} }
func (m *RegistrationResponse) String() string { return proto.CompactTextString(m) }
func (*RegistrationResponse) ProtoMessage()    {}
func (*RegistrationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_4ae8239b4bb1387c, []int{1}
}
func (m *RegistrationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegistrationResponse.Unmarshal(m, b)
}
func (m *RegistrationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegistrationResponse.Marshal(b, m, deterministic)
}
func (dst *RegistrationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistrationResponse.Merge(dst, src)
}
func (m *RegistrationResponse) XXX_Size() int {
	return xxx_messageInfo_RegistrationResponse.Size(m)
}
func (m *RegistrationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistrationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegistrationResponse proto.InternalMessageInfo

func (m *RegistrationResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegistrationResponse) GetAddr() string {
	if m != nil {
		return m.Addr
	}
	return ""
}

type SyncCheckRequest struct {
	LastVersion          int32    `protobuf:"varint,1,opt,name=lastVersion,proto3" json:"lastVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SyncCheckRequest) Reset()         { *m = SyncCheckRequest{} }
func (m *SyncCheckRequest) String() string { return proto.CompactTextString(m) }
func (*SyncCheckRequest) ProtoMessage()    {}
func (*SyncCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_4ae8239b4bb1387c, []int{2}
}
func (m *SyncCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncCheckRequest.Unmarshal(m, b)
}
func (m *SyncCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncCheckRequest.Marshal(b, m, deterministic)
}
func (dst *SyncCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncCheckRequest.Merge(dst, src)
}
func (m *SyncCheckRequest) XXX_Size() int {
	return xxx_messageInfo_SyncCheckRequest.Size(m)
}
func (m *SyncCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SyncCheckRequest proto.InternalMessageInfo

func (m *SyncCheckRequest) GetLastVersion() int32 {
	if m != nil {
		return m.LastVersion
	}
	return 0
}

type SyncCheckResponse struct {
	Version              int32                      `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Checks               []*SyncCheckResponse_Check `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *SyncCheckResponse) Reset()         { *m = SyncCheckResponse{} }
func (m *SyncCheckResponse) String() string { return proto.CompactTextString(m) }
func (*SyncCheckResponse) ProtoMessage()    {}
func (*SyncCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_4ae8239b4bb1387c, []int{3}
}
func (m *SyncCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncCheckResponse.Unmarshal(m, b)
}
func (m *SyncCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncCheckResponse.Marshal(b, m, deterministic)
}
func (dst *SyncCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncCheckResponse.Merge(dst, src)
}
func (m *SyncCheckResponse) XXX_Size() int {
	return xxx_messageInfo_SyncCheckResponse.Size(m)
}
func (m *SyncCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SyncCheckResponse proto.InternalMessageInfo

func (m *SyncCheckResponse) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SyncCheckResponse) GetChecks() []*SyncCheckResponse_Check {
	if m != nil {
		return m.Checks
	}
	return nil
}

type SyncCheckResponse_Check struct {
	Check                SyncCheckResponse_Check_CheckType `protobuf:"varint,1,opt,name=check,proto3,enum=SyncCheckResponse_Check_CheckType" json:"check,omitempty"`
	Uri                  string                            `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *SyncCheckResponse_Check) Reset()         { *m = SyncCheckResponse_Check{} }
func (m *SyncCheckResponse_Check) String() string { return proto.CompactTextString(m) }
func (*SyncCheckResponse_Check) ProtoMessage()    {}
func (*SyncCheckResponse_Check) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_4ae8239b4bb1387c, []int{3, 0}
}
func (m *SyncCheckResponse_Check) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SyncCheckResponse_Check.Unmarshal(m, b)
}
func (m *SyncCheckResponse_Check) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SyncCheckResponse_Check.Marshal(b, m, deterministic)
}
func (dst *SyncCheckResponse_Check) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SyncCheckResponse_Check.Merge(dst, src)
}
func (m *SyncCheckResponse_Check) XXX_Size() int {
	return xxx_messageInfo_SyncCheckResponse_Check.Size(m)
}
func (m *SyncCheckResponse_Check) XXX_DiscardUnknown() {
	xxx_messageInfo_SyncCheckResponse_Check.DiscardUnknown(m)
}

var xxx_messageInfo_SyncCheckResponse_Check proto.InternalMessageInfo

func (m *SyncCheckResponse_Check) GetCheck() SyncCheckResponse_Check_CheckType {
	if m != nil {
		return m.Check
	}
	return SyncCheckResponse_Check_HTTP
}

func (m *SyncCheckResponse_Check) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

type SaveCheckMetricsRequest struct {
	CheckId              string             `protobuf:"bytes,1,opt,name=checkId,proto3" json:"checkId,omitempty"`
	Metrics              map[string]float64 `protobuf:"bytes,2,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *SaveCheckMetricsRequest) Reset()         { *m = SaveCheckMetricsRequest{} }
func (m *SaveCheckMetricsRequest) String() string { return proto.CompactTextString(m) }
func (*SaveCheckMetricsRequest) ProtoMessage()    {}
func (*SaveCheckMetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_4ae8239b4bb1387c, []int{4}
}
func (m *SaveCheckMetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveCheckMetricsRequest.Unmarshal(m, b)
}
func (m *SaveCheckMetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveCheckMetricsRequest.Marshal(b, m, deterministic)
}
func (dst *SaveCheckMetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveCheckMetricsRequest.Merge(dst, src)
}
func (m *SaveCheckMetricsRequest) XXX_Size() int {
	return xxx_messageInfo_SaveCheckMetricsRequest.Size(m)
}
func (m *SaveCheckMetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveCheckMetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveCheckMetricsRequest proto.InternalMessageInfo

func (m *SaveCheckMetricsRequest) GetCheckId() string {
	if m != nil {
		return m.CheckId
	}
	return ""
}

func (m *SaveCheckMetricsRequest) GetMetrics() map[string]float64 {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type SaveCheckMetricsResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveCheckMetricsResponse) Reset()         { *m = SaveCheckMetricsResponse{} }
func (m *SaveCheckMetricsResponse) String() string { return proto.CompactTextString(m) }
func (*SaveCheckMetricsResponse) ProtoMessage()    {}
func (*SaveCheckMetricsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_4ae8239b4bb1387c, []int{5}
}
func (m *SaveCheckMetricsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveCheckMetricsResponse.Unmarshal(m, b)
}
func (m *SaveCheckMetricsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveCheckMetricsResponse.Marshal(b, m, deterministic)
}
func (dst *SaveCheckMetricsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveCheckMetricsResponse.Merge(dst, src)
}
func (m *SaveCheckMetricsResponse) XXX_Size() int {
	return xxx_messageInfo_SaveCheckMetricsResponse.Size(m)
}
func (m *SaveCheckMetricsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveCheckMetricsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveCheckMetricsResponse proto.InternalMessageInfo

func (m *SaveCheckMetricsResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*RegistrationRequest)(nil), "RegistrationRequest")
	proto.RegisterType((*RegistrationResponse)(nil), "RegistrationResponse")
	proto.RegisterType((*SyncCheckRequest)(nil), "SyncCheckRequest")
	proto.RegisterType((*SyncCheckResponse)(nil), "SyncCheckResponse")
	proto.RegisterType((*SyncCheckResponse_Check)(nil), "SyncCheckResponse.Check")
	proto.RegisterType((*SaveCheckMetricsRequest)(nil), "SaveCheckMetricsRequest")
	proto.RegisterMapType((map[string]float64)(nil), "SaveCheckMetricsRequest.MetricsEntry")
	proto.RegisterType((*SaveCheckMetricsResponse)(nil), "SaveCheckMetricsResponse")
	proto.RegisterEnum("SyncCheckResponse_Check_CheckType", SyncCheckResponse_Check_CheckType_name, SyncCheckResponse_Check_CheckType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GaiaClient is the client API for Gaia service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GaiaClient interface {
	Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error)
	SyncCheck(ctx context.Context, in *SyncCheckRequest, opts ...grpc.CallOption) (*SyncCheckResponse, error)
	SaveCheckMetrics(ctx context.Context, in *SaveCheckMetricsRequest, opts ...grpc.CallOption) (*SaveCheckMetricsResponse, error)
}

type gaiaClient struct {
	cc *grpc.ClientConn
}

func NewGaiaClient(cc *grpc.ClientConn) GaiaClient {
	return &gaiaClient{cc}
}

func (c *gaiaClient) Register(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*RegistrationResponse, error) {
	out := new(RegistrationResponse)
	err := c.cc.Invoke(ctx, "/Gaia/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gaiaClient) SyncCheck(ctx context.Context, in *SyncCheckRequest, opts ...grpc.CallOption) (*SyncCheckResponse, error) {
	out := new(SyncCheckResponse)
	err := c.cc.Invoke(ctx, "/Gaia/SyncCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gaiaClient) SaveCheckMetrics(ctx context.Context, in *SaveCheckMetricsRequest, opts ...grpc.CallOption) (*SaveCheckMetricsResponse, error) {
	out := new(SaveCheckMetricsResponse)
	err := c.cc.Invoke(ctx, "/Gaia/SaveCheckMetrics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GaiaServer is the server API for Gaia service.
type GaiaServer interface {
	Register(context.Context, *RegistrationRequest) (*RegistrationResponse, error)
	SyncCheck(context.Context, *SyncCheckRequest) (*SyncCheckResponse, error)
	SaveCheckMetrics(context.Context, *SaveCheckMetricsRequest) (*SaveCheckMetricsResponse, error)
}

func RegisterGaiaServer(s *grpc.Server, srv GaiaServer) {
	s.RegisterService(&_Gaia_serviceDesc, srv)
}

func _Gaia_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaiaServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gaia/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaiaServer).Register(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gaia_SyncCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaiaServer).SyncCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gaia/SyncCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaiaServer).SyncCheck(ctx, req.(*SyncCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gaia_SaveCheckMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCheckMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GaiaServer).SaveCheckMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Gaia/SaveCheckMetrics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GaiaServer).SaveCheckMetrics(ctx, req.(*SaveCheckMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Gaia_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Gaia",
	HandlerType: (*GaiaServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Gaia_Register_Handler,
		},
		{
			MethodName: "SyncCheck",
			Handler:    _Gaia_SyncCheck_Handler,
		},
		{
			MethodName: "SaveCheckMetrics",
			Handler:    _Gaia_SaveCheckMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_agent_4ae8239b4bb1387c) }

var fileDescriptor_agent_4ae8239b4bb1387c = []byte{
	// 423 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0x3a, 0x49, 0x93, 0x4c, 0xa0, 0x72, 0x87, 0x20, 0x16, 0x9f, 0xa2, 0x95, 0x90, 0x0a,
	0x12, 0x2b, 0x14, 0x7a, 0x28, 0x3d, 0x80, 0x4a, 0x15, 0xd1, 0x1e, 0x90, 0xaa, 0xad, 0xc5, 0x7d,
	0x49, 0x56, 0xc5, 0x4a, 0x6b, 0x87, 0xdd, 0x4d, 0x24, 0x5f, 0xf9, 0x22, 0xbe, 0x81, 0x6f, 0xe1,
	0x43, 0x2a, 0xef, 0xae, 0xab, 0x34, 0x89, 0x2f, 0xd6, 0xcc, 0xf8, 0xbd, 0x79, 0x7e, 0x33, 0x63,
	0x18, 0xca, 0x5b, 0x95, 0x5b, 0xbe, 0xd4, 0x85, 0x2d, 0xd8, 0x5b, 0x78, 0x21, 0xd4, 0x6d, 0x66,
	0xac, 0x96, 0x36, 0x2b, 0x72, 0xa1, 0x7e, 0xaf, 0x94, 0xb1, 0x88, 0xd0, 0xc9, 0xe5, 0xbd, 0xa2,
	0x64, 0x4c, 0x8e, 0x07, 0xc2, 0xc5, 0xec, 0x33, 0x8c, 0x9e, 0x42, 0xcd, 0xb2, 0xc8, 0x8d, 0xda,
	0x87, 0xad, 0x6a, 0x72, 0x3e, 0xd7, 0x34, 0xf2, 0xb5, 0x2a, 0x66, 0x27, 0x10, 0xdf, 0x94, 0xf9,
	0xec, 0xe2, 0x97, 0x9a, 0x2d, 0x6a, 0x9d, 0x31, 0x0c, 0xef, 0xa4, 0xb1, 0x3f, 0x94, 0x36, 0x59,
	0x91, 0xbb, 0x16, 0x5d, 0xb1, 0x59, 0x62, 0xff, 0x09, 0x1c, 0x6d, 0xd0, 0x82, 0x26, 0x85, 0xde,
	0xfa, 0x09, 0xa7, 0x4e, 0xf1, 0x03, 0x1c, 0xcc, 0x2a, 0xa8, 0xa1, 0xd1, 0xb8, 0x7d, 0x3c, 0x9c,
	0x50, 0xbe, 0xc3, 0xe6, 0x3e, 0x0b, 0xb8, 0xe4, 0x0f, 0x81, 0xae, 0xab, 0xe0, 0x29, 0x74, 0x5d,
	0xcd, 0xf5, 0x3c, 0x9c, 0xb0, 0x26, 0xaa, 0x7f, 0xa6, 0xe5, 0x52, 0x09, 0x4f, 0xc0, 0x18, 0xda,
	0x2b, 0x9d, 0x05, 0xbb, 0x55, 0xc8, 0xde, 0xc3, 0xe0, 0x11, 0x85, 0x7d, 0xe8, 0x5c, 0xa6, 0xe9,
	0x75, 0xdc, 0xc2, 0x1e, 0xb4, 0xd3, 0x8b, 0xeb, 0x98, 0xe0, 0x73, 0x18, 0x5c, 0x4e, 0xcf, 0x45,
	0xfa, 0x75, 0x7a, 0x9e, 0xc6, 0x11, 0xfb, 0x4b, 0xe0, 0xd5, 0x8d, 0x5c, 0x2b, 0xc7, 0xf9, 0xae,
	0xac, 0xce, 0x66, 0xa6, 0x1e, 0x12, 0x85, 0x9e, 0x53, 0xb9, 0x9a, 0x87, 0x19, 0xd7, 0x29, 0x7e,
	0x81, 0xde, 0xbd, 0xc7, 0x06, 0xb7, 0x6f, 0x78, 0x43, 0x13, 0x1e, 0xd2, 0x69, 0x6e, 0x75, 0x29,
	0x6a, 0x56, 0x72, 0x06, 0xcf, 0x36, 0x5f, 0x54, 0x3e, 0x16, 0xaa, 0x0c, 0x32, 0x55, 0x88, 0x23,
	0xe8, 0xae, 0xe5, 0xdd, 0x4a, 0x39, 0x6f, 0x44, 0xf8, 0xe4, 0x2c, 0x3a, 0x25, 0xec, 0x1d, 0xd0,
	0x5d, 0xb1, 0xb0, 0x9f, 0x43, 0x88, 0x0a, 0x3f, 0xc6, 0xbe, 0x88, 0x8a, 0xc5, 0xe4, 0x1f, 0x81,
	0xce, 0x37, 0x99, 0x49, 0xfc, 0x04, 0x7d, 0x7f, 0x44, 0x4a, 0xe3, 0x88, 0xef, 0x39, 0xbd, 0xe4,
	0x25, 0xdf, 0x77, 0x65, 0xac, 0x85, 0x27, 0x30, 0x78, 0xdc, 0x07, 0x1e, 0xf1, 0xed, 0x5b, 0x4a,
	0x70, 0x77, 0x5d, 0xac, 0x85, 0x57, 0x10, 0x6f, 0x7f, 0x25, 0xd2, 0xa6, 0x29, 0x25, 0xaf, 0x79,
	0x93, 0x25, 0xd6, 0xfa, 0x79, 0xe0, 0x7e, 0x99, 0x8f, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3e,
	0xf9, 0x09, 0x2a, 0x41, 0x03, 0x00, 0x00,
}
